# Generated by Django 5.0.4 on 2024-05-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id_veiculos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('marca', models.TextField(max_length=255)),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
