# Generated by Django 5.0.4 on 2024-05-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veiculos',
            new_name='Veiculo',
        ),
    ]
